language: python

python:
    - 2.7
    - 3.5

cache:
    directories:
        - $HOME/.cache/pip

env:
    - NUMPY_VERSION=1.11.1 OMP_NUM_THREADS=2

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose cython mpi4py numba
    - pip install pfft-python
    - python setup.py install

script: 
    - python install mpi4py_test
    - python runtests.py --mpirun="mpirun -np 9"
